import { useEffect, useMemo, useState } from "react";
import { MapContainer, ImageOverlay, GeoJSON, Marker, Polyline, Polygon, useMapEvents } from "react-leaflet";
import { CRS, divIcon } from "leaflet";

const API = import.meta.env.VITE_API_URL || "http://127.0.0.1:8000";
const BOUNDS = [[0, 0], [100, 100]];
const STORAGE_PREFIX = "sahinaksha:review:";

function featureType(f){const p=f?.properties||{};if(p.building_id!=null||p.feature_type==="building")return"building";if(p.road_id!=null||p.feature_type==="road"||p.feature_type==="road_evidence")return"road";return"parcel"}
function featureId(f){const p=f?.properties||{};return`${featureType(f)}:${p.parcel_id||p.building_id||p.road_id||f?.id||"unknown"}`}
function readStorage(k,f){try{const x=localStorage.getItem(k);return x?JSON.parse(x):f}catch{return f}}
function clone(x){return JSON.parse(JSON.stringify(x))}
function polygonArea(g){if(!g)return 0;const a=r=>Math.abs(r.reduce((s,p,i)=>{const q=r[(i+1)%r.length];return s+p[0]*q[1]-q[0]*p[1]},0))/2;if(g.type==="Polygon")return(g.coordinates||[]).reduce((s,r,i)=>s+(i?-a(r):a(r)),0);return 0}
function vertices(g){if(!g||g.type!=="Polygon")return[];return(g.coordinates[0]||[]).slice(0,-1).map((point,index)=>({index,point}))}
function moveVertex(g,index,point){const n=clone(g);n.coordinates[0][index]=point;if(index===0)n.coordinates[0][n.coordinates[0].length-1]=[...point];return n}
function insertVertex(g,index,point){const n=clone(g);n.coordinates[0].splice(index+1,0,point);return n}
function deleteVertex(g,index){const n=clone(g);if(n.coordinates[0].length<=4)return null;n.coordinates[0].splice(index,1);if(index===0)n.coordinates[0][n.coordinates[0].length-1]=[...n.coordinates[0][0]];return n}
const vertexIcon=divIcon({className:"geometry-vertex",html:"<span></span>",iconSize:[14,14],iconAnchor:[7,7]});
function EditorVertices({feature,onChange}){return<>{vertices(feature?.geometry).map(v=><Marker key={v.index} position={[v.point[1],v.point[0]]} icon={vertexIcon} draggable eventHandlers={{dragend:e=>{const p=e.target.getLatLng();onChange(moveVertex(feature.geometry,v.index,[p.lng,p.lat]))}}}/>)}</>}
function DrawCapture({active,onPoint}){useMapEvents({click:e=>{if(active)onPoint([e.latlng.lng,e.latlng.lat])}});return null}

const FIELDS={building:["building_id","building_use","floors","condition","occupancy","roof_type","address","survey_status","reviewer_notes"],road:["road_id","road_type","surface","access","condition","name","reviewer_notes"],parcel:["parcel_id","land_use","parcel_status","area","ownership_ref","survey_status","reviewer_notes"]};
const OPTIONS={building_use:["Residential","Commercial","Industrial","Institutional","Mixed Use","Other"],condition:["Good","Fair","Poor","Unknown"],occupancy:["Occupied","Vacant","Under Construction","Unknown"],roof_type:["Flat","Pitched","Metal","Tile","Concrete","Other","Unknown"],survey_status:["AI Detected","Human Verified","Needs Field Survey","Unknown"],road_type:["Highway","Main Road","Street","Lane","Path","Access Road","Unknown"],surface:["Asphalt","Concrete","Gravel","Dirt","Paved","Unknown"],access:["Public","Private","Restricted","Unknown"],land_use:["Residential","Commercial","Agricultural","Industrial","Institutional","Vacant","Mixed Use","Unknown"],parcel_status:["Preliminary Block","Reference Parcel","Human Verified","Needs Survey"]};

export default function Dashboard({result,onReset}){
 const storageKey=`${STORAGE_PREFIX}${result.analysis_id||"current"}`;
 const original=useMemo(()=>({parcels:result.parcels||{type:"FeatureCollection",features:[]},buildings:result.buildings||{type:"FeatureCollection",features:[]},roads:result.roads||{type:"FeatureCollection",features:[]}}),[result]);
 const [layers,setLayers]=useState({parcels:true,buildings:true,roads:true});
 const [geometry,setGeometry]=useState(()=>readStorage(`${storageKey}:geometry`,{}));
 const [manualFeatures,setManualFeatures]=useState(()=>readStorage(`${storageKey}:manual_features`,[]));
 const [review,setReview]=useState(()=>readStorage(`${storageKey}:decisions`,{}));
 const [edits,setEdits]=useState(()=>readStorage(`${storageKey}:edits`,{}));
 const [selected,setSelected]=useState(null); const [editing,setEditing]=useState(false); const [fontScale,setFontScale]=useState(1); const [drawMode,setDrawMode]=useState(false); const [drawPoints,setDrawPoints]=useState([]); const [history,setHistory]=useState([]); const [future,setFuture]=useState([]); const [message,setMessage]=useState(""); const [reviewer,setReviewer]=useState(()=>localStorage.getItem(`${storageKey}:reviewer`)||""); const [finalMap,setFinalMap]=useState(false);
 useEffect(()=>{try{localStorage.setItem(`${storageKey}:geometry`,JSON.stringify(geometry));localStorage.setItem(`${storageKey}:manual_features`,JSON.stringify(manualFeatures));localStorage.setItem(`${storageKey}:decisions`,JSON.stringify(review));localStorage.setItem(`${storageKey}:edits`,JSON.stringify(edits));localStorage.setItem(`${storageKey}:reviewer`,reviewer)}catch{}},[storageKey,geometry,manualFeatures,review,edits,reviewer]);
 const all=useMemo(()=>[...Object.entries(original).flatMap(([type,c])=>(c.features||[]).map(f=>({...f,__type:type,geometry:geometry[featureId(f)]||f.geometry}))),...manualFeatures.map(f=>({...f,__type:featureType(f),geometry:geometry[featureId(f)]||f.geometry}))],[original,geometry,manualFeatures]);
 const current=selected?all.find(f=>featureId(f)===featureId(selected)):null; const currentId=current?featureId(current):"";
 const total=all.length, reviewed=Object.keys(review).length, approved=Object.values(review).filter(v=>v==="Approved").length; const parcelFeatures=result.parcels?.features||[]; const reviewScores=parcelFeatures.map(f=>f.properties?.review_score).filter(v=>typeof v==="number"); const areaSqM=parcelFeatures.map(f=>f.properties?.area_sq_m).filter(v=>typeof v==="number"); const meanReview=reviewScores.length?(reviewScores.reduce((a,b)=>a+b,0)/reviewScores.length).toFixed(1):"—"; const totalAreaSqM=areaSqM.length?areaSqM.reduce((a,b)=>a+b,0).toFixed(2):"—"; const validationIssues=result.validation?.issues?.length||0;
 const select=f=>{setSelected(f);setEditing(false);setDrawMode(false);setDrawPoints([]);setHistory([]);setFuture([])};
 const applyGeometry=g=>{if(!currentId)return;setHistory(h=>[...h,(geometry[currentId]||current.geometry)].slice(-30));setFuture([]);setGeometry(x=>({...x,[currentId]:g}));setSelected(x=>x?{...x,geometry:g}:x);setMessage("Boundary updated and saved locally ✓")};
 const undo=()=>{if(!history.length)return;const prev=history.at(-1);setFuture(f=>[geometry[currentId]||current.geometry,...f]);setHistory(h=>h.slice(0,-1));setGeometry(g=>({...g,[currentId]:prev}));setSelected(s=>s?{...s,geometry:prev}:s)};
 const redo=()=>{if(!future.length)return;const next=future[0];setHistory(h=>[...h,(geometry[currentId]||current.geometry)].slice(-30));setFuture(f=>f.slice(1));setGeometry(g=>({...g,[currentId]:next}));setSelected(s=>s?{...s,geometry:next}:s)};
 const addVertex=()=>{if(!current||current.geometry.type!=="Polygon")return setMessage("This feature is not a polygon.");const vs=vertices(current.geometry);if(!vs.length)return;const v=vs[vs.length-1],n=vs[0];const p=[(v.point[0]+n.point[0])/2,(v.point[1]+n.point[1])/2];applyGeometry(insertVertex(current.geometry,v.index,p));};
 const deleteVertexAction=()=>{if(!current)return;const vs=vertices(current.geometry);if(vs.length<=3)return setMessage("A polygon must keep at least 3 vertices.");const g=deleteVertex(current.geometry,vs.length-1);if(g)applyGeometry(g)};
 const resetGeometry=()=>{const source=(original[current?.__type]?.features||[]).find(f=>featureId(f)===currentId);if(source)applyGeometry(source.geometry);else{const manual=manualFeatures.find(f=>featureId(f)===currentId);if(manual)applyGeometry(manual.geometry)}};
 const finalFeatures=all.filter(f=>review[featureId(f)]==="Approved").map(f=>({...f,geometry:geometry[featureId(f)]||f.geometry,properties:{...f.properties,...(edits[featureId(f)]||{}),review_status:"Approved",reviewed_by:reviewer||"not specified"}}));
 const download=()=>{if(!approved){setMessage("Approve at least one feature before downloading the final reviewed GIS.");document.getElementById("dashboard-workspace")?.scrollIntoView({behavior:"smooth",block:"start"});return;}const out={type:"FeatureCollection",features:finalFeatures,metadata:{project:"SahiNaksha",analysis_id:result.analysis_id,stage:"human_reviewed_geometry",approved_feature_count:finalFeatures.length,geometry_edited_feature_count:Object.keys(geometry).length,manual_feature_count:manualFeatures.length,legal_status:"prototype_output_requires_authoritative_cadastral_and_survey_validation"}};const u=URL.createObjectURL(new Blob([JSON.stringify(out,null,2)],{type:"application/geo+json"}));const a=document.createElement("a");a.href=u;a.download=`sahinaksha_final_${result.analysis_id||"output"}.geojson`;a.click();URL.revokeObjectURL(u)};
 const drawPoint=p=>setDrawPoints(x=>[...x,p]);
 const finishDraw=()=>{if(drawPoints.length<3)return setMessage("Place at least 3 points.");const type=current?featureType(current):"parcel";const stamp=Date.now();const id=`${type}:manual-${stamp}`;const f={type:"Feature",id:`manual-${stamp}`,properties:{feature_type:type,review_status:"Needs Review"},geometry:{type:"Polygon",coordinates:[[...drawPoints,drawPoints[0]]]}};setManualFeatures(x=>[...x,f]);setReview(r=>({...r,[id]:"Needs Review"}));setDrawPoints([]);setDrawMode(false);setSelected(f);setMessage("New polygon created and marked Needs Review ✓")};
 const label=k=>k.replaceAll("_"," ").replace(/\b\w/g,x=>x.toUpperCase());
 const jump=id=>document.getElementById(id)?.scrollIntoView({behavior:"smooth",block:"start"});\n return <main className="dashboard gov-portal" style={{fontSize:`${fontScale}em`}}><div className="gov-top-strip"><div>भारत सरकार &nbsp;|&nbsp; Government of India</div><div className="gov-tools"><button type="button" onClick={()=>jump("dashboard-workspace")}>Skip to main content</button><button type="button" onClick={()=>setFontScale(v=>Math.max(.9,v-.05))}>A−</button><button type="button" onClick={()=>setFontScale(1)}>A</button><button type="button" onClick={()=>setFontScale(v=>Math.min(1.15,v+.05))}>A+</button></div></div><header className="gov-header dashboard-header"><div className="gov-brand"><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Government_of_India_logo.svg/120px-Government_of_India_logo.svg.png" alt="Government of India emblem" /><div><div className="gov-hindi">ग्रामीण विकास मंत्रालय</div><div className="gov-title">MINISTRY OF RURAL DEVELOPMENT</div><div className="gov-subtitle">GOVERNMENT OF INDIA</div></div></div><div className="header-identity"><img className="ministry-logo" src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Ministry_of_Rural_Development.png/250px-Ministry_of_Rural_Development.png" alt="Ministry of Rural Development logo" /><div className="sahinaksha-brand"><strong>SahiNaksha</strong><span>AI-Assisted Cadastral Mapping</span></div></div></header><nav className="gov-nav"><button type="button" onClick={()=>window.scrollTo({top:0,behavior:"smooth"})}>Dashboard</button><button type="button" onClick={()=>jump("dashboard-workspace")}>Land &amp; Survey</button><button type="button" onClick={()=>jump("dashboard-workspace")}>GIS Layers</button><button type="button" onClick={()=>jump("dashboard-report")}>Validation</button><button type="button" onClick={()=>jump("dashboard-report")}>Reports</button><button type="button" onClick={()=>jump("dashboard-help")}>Help &amp; Support</button></nav><div className="gov-notice"><b>Prototype Portal</b> — SIH 2026 demonstration system; not an official Government of India service.</div><header className="topbar"><div><div className="brand">Sahi<span>Naksha</span></div><small>Digital cadastral mapping • GIS review &amp; validation</small></div><div className="actions"><button className="secondary-button" onClick={()=>setFinalMap(v=>!v)}>{finalMap?"Show AI Map":"Final Reviewed Map"}</button><button className="secondary-button" onClick={download} disabled={!approved}>Download Final GIS</button><button className="secondary-button" onClick={onReset}>New Analysis</button></div></header>
 <section className="summary-grid"><div><b>{original.parcels.features.length+manualFeatures.filter(f=>featureType(f)==="parcel").length}</b><span>Parcel Blocks</span></div><div><b>{original.buildings.features.length+manualFeatures.filter(f=>featureType(f)==="building").length}</b><span>Buildings</span></div><div><b>{original.roads.features.length+manualFeatures.filter(f=>featureType(f)==="road").length}</b><span>Roads / Access</span></div><div><b>{reviewed}/{total}</b><span>Reviewed</span></div></section>
 <section id="dashboard-report" className="report-grid" style={{margin:"14px 24px 0"}}><div className="report-card"><b>{meanReview}</b><span>Mean review score</span><small>Human-review priority, not AI accuracy.</small></div><div className="report-card"><b>{totalAreaSqM==="—"?"Not available":totalAreaSqM+" m²"}</b><span>Total parcel area</span><small>{areaSqM.length?"Computed from projected CRS":"Requires valid georeferencing/CRS."}</small></div><div className="report-card"><b>{validationIssues}</b><span>Validation issues</span><small>Review before final GIS export.</small></div><div className="report-card"><b>{result.topology_stats?.overlap_conflicts_resolved||0}</b><span>Overlap conflicts resolved</span><small>Topology repair pass.</small></div></section><section className="editor-banner"><div><b>Interactive Map Editor</b><span>Correct AI geometry directly against the aerial image. Drag points, add/delete vertices, undo/redo, reset, or draw a new polygon.</span></div><div className="editor-tools"><button className="secondary-button" disabled={!current||finalMap} onClick={()=>setEditing(v=>!v)}>{editing?"Exit Edit":"Edit Boundary"}</button><button className="secondary-button" disabled={!editing} onClick={addVertex}>＋ Vertex</button><button className="secondary-button" disabled={!editing} onClick={deleteVertexAction}>− Vertex</button><button className="secondary-button" disabled={!editing||!history.length} onClick={undo}>↶ Undo</button><button className="secondary-button" disabled={!editing||!future.length} onClick={redo}>↷ Redo</button><button className="secondary-button" disabled={!editing} onClick={resetGeometry}>Reset AI</button><button className="secondary-button" disabled={finalMap} onClick={()=>{setDrawMode(v=>!v);setDrawPoints([])}}>{drawMode?"Cancel Draw":"Draw New"}</button>{drawMode&&<button className="primary-button inline-button" onClick={finishDraw}>Finish</button>}</div>{message&&<small className="editor-message">{message}</small>}</section>
 <section id="dashboard-workspace" className="workspace"><aside className="sidebar"><h3>GIS Layers</h3>{Object.keys(layers).map(k=><label className="toggle" key={k}><input type="checkbox" checked={layers[k]} onChange={()=>setLayers(x=>({...x,[k]:!x[k]}))}/>{k}</label>)}<hr/><h3>Feature Review</h3>{current?<><div className="selected-title"><span className="feature-type-badge">{featureType(current)}</span><b>{currentId}</b></div><div className="details">{FIELDS[featureType(current)].map(k=><label className="edit-field" key={k}><span>{label(k)}</span>{OPTIONS[k]?<select value={edits[currentId]?.[k]??current.properties?.[k]??""} onChange={e=>setEdits(x=>({...x,[currentId]:{...(x[currentId]||{}),[k]:e.target.value}}))}><option value="">Select...</option>{OPTIONS[k].map(o=><option key={o}>{o}</option>)}</select>:<input value={edits[currentId]?.[k]??current.properties?.[k]??""} onChange={e=>setEdits(x=>({...x,[currentId]:{...(x[currentId]||{}),[k]:e.target.value}}))}/>}</label>)}</div><label className="reviewer-field"><span>Reviewer</span><input value={reviewer} onChange={e=>setReviewer(e.target.value)} placeholder="Reviewer name"/></label><div className="review-buttons"><button onClick={()=>setReview(x=>({...x,[currentId]:"Approved"}))}>✓ Approve</button><button onClick={()=>setReview(x=>({...x,[currentId]:"Needs Review"}))}>⚠ Needs Review</button><button onClick={()=>setReview(x=>({...x,[currentId]:"Rejected"}))}>✕ Reject</button></div>{review[currentId]&&<p className="review-status">{review[currentId]} · saved locally</p>}<div className="geometry-help"><b>Boundary accuracy</b><span>White points are draggable vertices.</span><span>＋ adds a corner. − removes a corner.</span><span>Undo/Redo protects previous geometry.</span><span>Area: {polygonArea(current.geometry).toFixed(2)} image units²</span></div></>:<p className="muted">Click a building, road or parcel on the image to select it.</p>}<hr/><p className="muted">Geometry, attributes, manual features and review decisions persist in this browser.</p></aside>
 <div className="map-wrap"><MapContainer crs={CRS.Simple} bounds={BOUNDS} minZoom={-2} maxZoom={5} zoom={0} style={{height:"100%",width:"100%"}}><DrawCapture active={drawMode} onPoint={drawPoint}/>{result.original_image_url&&<ImageOverlay url={result.original_image_url} bounds={BOUNDS} opacity={.92}/>} {!finalMap&&layers.parcels&&<GeoJSON data={{type:"FeatureCollection",features:all.filter(f=>featureType(f)==="parcel")}} style={{color:"#22c55e",weight:2.5,fillOpacity:.08}} onEachFeature={(f,l)=>l.on({click:()=>select(f)})}/>} {!finalMap&&layers.buildings&&<GeoJSON data={{type:"FeatureCollection",features:all.filter(f=>featureType(f)==="building")}} style={{color:"#38bdf8",weight:2,fillOpacity:.08}} onEachFeature={(f,l)=>l.on({click:()=>select(f)})}/>} {!finalMap&&layers.roads&&<GeoJSON data={{type:"FeatureCollection",features:all.filter(f=>featureType(f)==="road")}} style={{color:"#f59e0b",weight:3,fillOpacity:.06}} onEachFeature={(f,l)=>l.on({click:()=>select(f)})}/>} {finalMap&&<GeoJSON data={{type:"FeatureCollection",features:finalFeatures}} style={{color:"#72d89b",weight:3,fillOpacity:.12}}/>}{editing&&current&&<EditorVertices feature={{...current,geometry:geometry[currentId]||current.geometry}} onChange={applyGeometry}/>} {drawMode&&drawPoints.length>1&&<Polyline positions={drawPoints.map(p=>[p[1],p[0]])} weight={2} dashArray="5 5"/>}{drawMode&&drawPoints.length>=3&&<Polygon positions={drawPoints.map(p=>[p[1],p[0]])} fillOpacity={.08} weight={1}/>}</MapContainer><div className="map-note">{drawMode?"Draw mode: click corners on the image, then Finish.":editing?"Edit mode: drag white vertices directly on the image.":finalMap?"Final reviewed map: approved features only.":"Select a feature to edit its boundary and attributes."}</div></div></section><footer id="dashboard-help" className="gov-footer"><div><b>Government of India</b><br/>Ministry of Rural Development • SahiNaksha Demonstration Portal</div><div>Privacy Policy &nbsp;|&nbsp; Terms &nbsp;|&nbsp; Accessibility &nbsp;|&nbsp; Contact</div></footer></main>;
}
